language: node_js

# 是否需要超级管理员权限
sudo: false

cache:
  # 需要缓存
  apt: true
  # 缓存目录
  directories:
    - node_modules

# 用到的 nodejs 版本
node_js: stable

# 安装依赖
install:
  - yarn install -D
  - cd ./test/smoke/template
  - yarn install -D
  - cd ../../../

# 跑一下测试
scripts:
  - npm test